controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

graphql:
    path: /graphql
    controller: Overblog\GraphQLBundle\Controller\GraphController::endpointAction

playground:
    path: /playground
    controller: App\Controller\GraphQLController::playground
    methods: GET