---
imports:
  - resource: services/

services:
    _defaults:
        public: false
        autowire: true
        autoconfigure: true

    App\Controller\:
        resource: '../src/Controller/*.php'
